I1=imread('C:\Users\owner\Desktop\ime\Time1.bmp');
I2=imread('C:\Users\owner\Desktop\ime\Time2.bmp');
[t1 t2]=size(I1);
figure
subplot(131);
imshow(I1);
title('image 1');
subplot(132);
imshow(I2);
title('image 2');
Ix=I1(:);
Iy=I2(:);
I=[Ix Iy];
Ix=double(Ix);
Iy=double(Iy);
u1=sum(Ix)/(t1*t1);
u2=sum(Iy)/(t1*t1);
c1=sum((Ix(:,1)-u1).*(Ix(:,1)-u1));
c2=sum((Ix(:,1)-u1).*(Iy(:,1)-u2));
c3=sum((Iy(:,1)-u2).*(Ix(:,1)-u1));
c4=sum((Iy(:,1)-u2).*(Iy(:,1)-u2));
c=[c1 c2;c3 c4];
c=c./(t1*t1-1);
b=eig(c);
k=max(max(b));
d=c-k*[1 0;0 1];
e=null(d);
e=e./(sum(e));
In=I1*e(1,1)+I2*e(2,1);
subplot(133);
imshow(In);
title('fusion');
